remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

title: Sebastian Malmqvist
description: Some basic examples of client interfaces to a computer vision API

author:
  name: Furiek
